<?php
/**
 * Copyright (c) Bruno Pelaquin. All rights reserved.
 * https://github.com/https-pelaquin
 * @var Pelaquin\EnhancedInstallments\Block\Product\PriceDiscount $block
 */
$product = $block->getProduct();
$productId = $product->getId();
$pixDiscount = $block->getDiscountData($product, 'pix', 'bp_pix_discount');
$bankSlipDiscount = $block->getDiscountData($product, 'boleto', 'bp_bank_slip_discount');

?>

<!-- <div class="price-box price-tier_price" data-role="priceBox" data-product-id="<?= $productId ?>" data-price-box="product-id-<?= $productId ?>">
    <div data-role="tier-price-block"></div>
</div> -->

<!-- <span data-role="priceBox" class="price" style="display: none"><?= $block->priceForGoogleMerchantCenter($block->getFinalPrice()) ?></span> -->

<?php if ($block->validateBiggestDiscount() == 'pixDiscount'): ?>
    <div class="main-price-discount">
        <span id="bp-pix-price" data-role="priceBox" data-price-type="finalPrice" class="price-wrapper"></span>

        <div class="msg-discount"><?= __('special pix price with %1% discount', $pixDiscount) ?></div>
    </div>

    <div class="msg-discount-wrapper">
        <div class="msg-discount"><strong id="bp-bank-slip-discount" data-role="priceBox"></strong>
            <?= __('special bank slip price with %1% discount', $bankSlipDiscount) ?>
        </div>
    </div>

<?php else: ?>

    <div class="main-price-discount">
        <span id="bp-bank-slip-discount" data-role="priceBox" data-price-type="finalPrice" class="price-wrapper">
        </span>

        <div class="msg-discount"><?= __('special bank slip price with %1% discount', $bankSlipDiscount) ?></div>
    </div>

    <div class="msg-discount-wrapper">
        <div class="msg-discount"><strong id="bp-pix-price" data-role="priceBox"></strong>
            <?= __('special pix price with %1% discount', $pixDiscount) ?>
        </div>
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "#bp-pix-price": {
            "bpPriceDiscount": {
                "priceConfig": <?= $block->getJsonConfig($product) ?>,
                "priceBoxSelector": "[data-price-box='product-id-<?= $productId ?>']",
                "productPrice": <?= $block->getFinalPrice() ?>,
                "priceTemplate": "<span class='price' style='display: inline-block;'><strong> <%- data.price %> </strong></span>",
                "discount" :  <?= $pixDiscount ?>
            }
        },
        "#bp-bank-slip-discount": {
            "bpPriceDiscount": {
                "priceConfig": <?= $block->getJsonConfig($product) ?>,
                "priceBoxSelector": "[data-price-box='product-id-<?= $productId ?>']",
                "productPrice": <?= $block->getFinalPrice() ?>,
                "priceTemplate": "<span class='price' style='display: inline-block;'><strong> <%- data.price %></strong></span>",
                "discount" :  <?= $bankSlipDiscount ?>
            }
        }
    }
</script>